name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Determine Simple Features Repository
      uses: frabert/replace-string-action@master
      id: sf-repository
      with:
        pattern: 'geojson-'
        string: "${{ github.repository }}"
        replace-with: ''
    - name: Checkout Simple Features Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ steps.sf-repository.outputs.replaced }}
        ref: ${{ github.ref }}
        path: simple-features-java
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Build & Install Simple Features
      run: mvn -f simple-features-java clean install -DskipTests
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build
      run: mvn clean package -DskipTests
